### ISSUE TITLE
remove dependency to ExUnit

### ISSUE THREAD

**Issue by chrisjowen** [PSPDFKit-labs/bypass#37]
Hey, 

First off thanks for the library its useful, good work. I was wondering if you could remove the dependency on `ExUnit`, I and several others use https://github.com/antonmi/espec as my testing framework and the `ExUnit.Callbacks.on_exit` check you do obviously blows up for me as I have no process running for `ExUnit`. 

I understand the value this callback and see your verifying calls here and even if the dependency remained it would be nice if this was an explicit call and not wired into the ExUnits on_exit calback

**Comment by alco** [comment]
Hi Chris,

What is an equivalent way of checking that the expectation function has been called when using espec?

**Comment by chrisjowen** [comment]
Just looking and it doesn't seem like there is an equivalent of the on_exit callback. Honestly, I just pulled this out on a fork because I didn't care about calls that shouldn't have been made because I was confident there were none and the ones I expected to be called would have failed my tests if not anyway because of the behaviour I added to the mock. 

I understand the value of this though, but could it not be explicitly called i.e. `Bypass.ensure_all_calls/1` or whatever, instead of relying on callback hooks?

**Comment by MSch** [comment]
Hi Chris,

When using Bypass with ExUnit we definitely want to keep the default behavior, but I am open to accepting PRs that make Bypass support espec out of the box.

**Comment by tompave** [comment]
Hi, I would love to see support for ESpec added to this library.

I've found out about Bypass today and I think it's an incredibly helpful too. It does exactly what I need, and it was a bad surprise to see it crash because it's hard-wired to ExUnit.

I think that for the moment I'll just disable that functionality in a fork, like @chrisjowen has done. I only need a simple stubbed HTTP server on localhost and don't really need expectations on the calls.

Maybe it would be nice to introduce an `allow` or `stub` API that does the same job of `expect`, but without setting expectations, so that users can choose.

> What is an equivalent way of checking that the expectation function has been called when using espec?

I'm not sure, but perhaps @antonmi, ESpec's author, may be able to give us some pointers.

**Comment by tompave** [comment]
Apparently there was another issue (https://github.com/PSPDFKit-labs/bypass/issues/9) on the same topic. That contains some more info on a possible implementation.

Is there any chance or interest in seeing this implemented? What approach should a pull request adopt? Using different adapters probably makes sense.

**Comment by MSch** [comment]
Thanks again @tompave - I just released 0.8.0 of bypass with your ESpec support included ❤️
